name=PulseWire Communication Library
version=1.0.0
author=Phil Schatzmann
maintainer=Phil Schatzmann 
license=MIT
sentence=Manchester IR transceiver library for Arduino, ESP32, RP2040.
paragraph=Supports generic interrupt-based and ESP32 RMT hardware drivers, with Stream interface and frame management.
category=Communication
url=https://github.com/pschatzmann/IRTransceiver
architectures=*
